services:
  navoda-erp-api-dev:
    container_name: navoda-erp-api-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DEV_PORT}:3000"
    environment:
      NODE_ENV: development
    profiles:
      - development

  navoda-erp-api-prod:
    container_name: navoda-erp-api-prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PROD_PORT}:3000"
    environment:
      NODE_ENV: production
    profiles:
      - production
